INDICES EJEMPLOS

EJEMPLO 1 
CREAR INDICE AGRUPADO UNICO PARA CAMPO CODIGO EN LA TABLA LIBROS

CREATE UNIQUE CLUSTERED INDEX I_libros_codigo ON LIBROS(CODIGO)
							NOMBRE DEL INDICE -- NOMBRE TABLA (COLUMNA DE LA TABLA)

EJEMPLO 2 
CREAR INDICE NO AGRUPADO UNICO PARA CAMPO TITULO EN LA TABLA LIBROS

CREATE NONCLUSTERED INDEX I_libros_ titulo ON LIBROS(TITULO)
				NOMBRE INDICE NO AGRUPADPO -- NOMBRE TABLA (COLUMNA DE LA TABLA)

EJEMPLO 3
CREAR UN INDICE COMPUESTO PARA EL CAMPO AUTOR Y EDITORIAL

CREATE INDEX I_libros_autoreditorial ON LIBROS(AUTOR, EDITORIAL)
			 NOMBRE INDICE COMPUESTO -- NOMBRE TABLA (COLUMNAS COMPUESTAS)

PARA VISUALIZAR LOS INDICES DE UNA TABLA SI ES AGRUPADA O NO AGRUPADA

sp_helpindex LIBROS:
			 NOMBRE DE LA TABLA

PARA VISUALIZAR TODOS LOS INDICES DE LA BASE DE DATOS
SELECT NAME FROM sysindexes;
