/*CREACION DE BASE DE DATOS PEDIDOS*/
CREATE DATABASE BIBLIOTECA
GO
/*INDICAMOS QUE UTILIZAREMOS LA BASE DE DATOS PEDIDO*/
USE BIBLIOTECA
GO
/*CREACION DE TABLAS*/
CREATE TABLE LECTOR(
	Id_Lector INTEGER PRIMARY KEY IDENTITY(1,1),/*DENOTAMOS QUE SERA LLAVE PRIMARIA AUTOINCREMENTAL EN 1*/
	Nombre_Lector VARCHAR(200) NOT NULL,
	Ciudad VARCHAR(25) NOT NULL,
	Telefono VARCHAR(9) NULL,
);

CREATE TABLE PRESTAMO(
	Id_Prestamo INTEGER PRIMARY KEY IDENTITY(1,1),/*DENOTAMOS QUE SERA LLAVE PRIMARIA AUTOINCREMENTAL EN 1*/
	Fecha_Prestamo DATE NOT NULL,
	Total_Importe FLOAT NOT NULL,
	Id_Lector INTEGER NOT NULL,
	CONSTRAINT fk_prestamo_lector FOREIGN KEY (Id_Lector) REFERENCES LECTOR(Id_Lector)/*RELACIONAMOS CON TABLA LECTOR*/
);

CREATE TABLE LIBRO(
	ISBN VARCHAR(20) PRIMARY KEY ,
	Titulo_Libro VARCHAR(50) NOT NULL,
	Autor_Libro VARCHAR(200) NOT NULL,
	Precio_ALQ FLOAT NOT NULL,
	Existencia TINYINT NOT NULL
);

CREATE TABLE DETALLE_PRESTAMO(
	Id_DetallePrestamo INTEGER PRIMARY KEY IDENTITY(1,1),/*DENOTAMOS QUE SERA LLAVE PRIMARIA AUTOINCREMENTAL EN 1*/
	Fecha_Devolucion DATE NOT NULL,
	Id_Prestamo INTEGER NOT NULL,
	ISBN VARCHAR(20) NOT NULL,
	CONSTRAINT fk_detalle_prestamo_prestamo FOREIGN KEY (Id_Prestamo) REFERENCES PRESTAMO(Id_Prestamo),/*RELACIONAMOS CON TABLA PRESTAMO*/
	CONSTRAINT fk_detalle_prestamo_libro FOREIGN KEY (ISBN) REFERENCES LIBRO(ISBN)/*RELACIONAMOS CON TABLA LIBRO*/
);